version: '3'
services:
  db:
    image: mysql
    ports: 
      - 3306:3306
    volumes: 
      - ./storage/db:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.defs.json:/etc/rabbitmq/rabbit_definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./storage/rabbitmq1:/var/lib/rabbitmq
    working_dir: /var/lib/rabbitmq
volumes:
  db:
  rabbitmq: